<?php
/**
 * File: includes/admin-page.php
 * Description: Contains the HTML and PHP code for the admin page of the WordPress Performance Checker plugin.
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// Define the function to render the admin page
function dmuk_bo_admin_page() {
    // Handle form submissions
    if ( isset( $_POST['dmuk_bo_create_posts'] ) && check_admin_referer( 'dmuk_bo_create_posts_nonce' ) ) {
        $num_posts = isset( $_POST['dmuk_bo_num_posts'] ) ? intval( $_POST['dmuk_bo_num_posts'] ) : 0;
        $num_words = isset( $_POST['dmuk_bo_num_words'] ) ? intval( $_POST['dmuk_bo_num_words'] ) : 0;
        $category_id = isset( $_POST['dmuk_bo_category'] ) ? intval( $_POST['dmuk_bo_category'] ) : 0;

        // Validate inputs
        if ( $num_posts > 0 && $num_posts <= 1000 && $num_words > 0 && $num_words <= 100 && $category_id > 0 ) {
            dmuk_bo_create_posts( $num_posts, $num_words, $category_id );
            // Clear feedback message after creating posts
            update_option( 'dmuk_bo_feedback', get_option('dmuk_bo_feedback') ); 
        } else {
            update_option( 'dmuk_bo_feedback', 'Invalid input values. Please ensure all inputs are filled in correctly.' );
        }
    } elseif ( isset( $_POST['dmuk_bo_delete_posts'] ) && check_admin_referer( 'dmuk_bo_delete_posts_nonce' ) ) {
        dmuk_bo_delete_posts();
        // Clear feedback message after deleting posts
        update_option( 'dmuk_bo_feedback', get_option('dmuk_bo_feedback') ); 
    }

    // Fetch feedback message
    $feedback = get_option( 'dmuk_bo_feedback', '' );
    
    // Fetch the current database size
    $total_size = dmuk_bo_get_database_size();
    ?>
    <div class="wrap">
        <h1>WordPress Performance Checker</h1>
        <p>This Diversify.me.uk (DMUK) plugin creates bulk posts with content generated by "Lorem Ipsum" text generator, 
		to enable testing WordPress websites and plugins with larger databases. Bulk posts can be created, automatically allocated to test categories, 
		and deleted at the click of a button without affecting existing posts. However, we recommend not testing on a live system, or doing a backup before you start testing.</p>
        
        <!-- Help Links -->
		<div style="display: flex; gap: 100px;">
			<a href="https://diversify.me.uk/wordpress-performance-checker-plugin-help/" target="_blank" class="button button-help">
				<span class="dashicons dashicons-editor-help"></span> Help
			</a>
			<a href="https://diversify.me.uk/donate/" target="_blank" class="button button-help">
				<span class="dashicons dashicons-smiley"></span> Donate
			</a>
		</div>

        
        <!-- Display the database size -->
        <div class="notice notice-info">
            <p>Current database size: <?php echo esc_html( $total_size ); ?> MB</p>
        </div>
        
        <?php if ( ! empty( $feedback ) ): ?>
            <div class="notice notice-success is-dismissible">
                <p><?php echo esc_html( $feedback ); ?></p>
            </div>
        <?php endif; ?>
        
        <!-- Form to create posts -->
        <form method="post">
            <?php wp_nonce_field( 'dmuk_bo_create_posts_nonce' ); ?>
            <h2>Create Test Posts</h2>
            <table class="form-table">
                <tr>
                    <th><label for="dmuk_bo_num_posts">Number of Posts</label></th>
                    <td>
                        <input type="number" id="dmuk_bo_num_posts" name="dmuk_bo_num_posts" min="1" max="1000" required>
                        <p class="description">Enter a number between 1 and 1000 for this batch. You can add more posts in subsequent batches, 
						but, since the unique number appended to each post title is 6 digits, the total number of test posts should not exceed 999,999 
						or posts could contain duplicate names and therefore produce unpredictable results.</p>
                    </td>
                </tr>
                <tr>
                    <th><label for="dmuk_bo_num_words">Number of paragraphs per Post</label></th>
                    <td>
                        <input type="number" id="dmuk_bo_num_words" name="dmuk_bo_num_words" min="1" max="100" required>
                        <p class="description">Enter a number between 1 and 100 for paragraphs per post. Each paragraph is simply the same 100 words from Lorem Ipsum, 
						repeated. So, each paragraph is about 800 bytes or just under 1kB.</p>
                    </td>
                </tr>
                <tr>
                    <th><label for="dmuk_bo_category">Test Category</label></th>
                    <td>
                        <select id="dmuk_bo_category" name="dmuk_bo_category" required>
                            <option value="">Select Category</option>
                            <?php
                            // Fetch categories for the dropdown
                            $categories = get_terms( array(
                                'taxonomy'   => 'category',
                                'hide_empty' => false,
                                'name__like' => 'WPPT Test Cat', // Fetch only test categories
                                'orderby'    => 'name',
                                'order'      => 'ASC',
                            ) );
                            foreach ( $categories as $category ) : ?>
                                <option value="<?php echo esc_attr( $category->term_id ); ?>">
                                    <?php echo esc_html( $category->name ); ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                </tr>
            </table>
            <input type="submit" name="dmuk_bo_create_posts" class="button button-primary" value="Create Test Posts">
        </form>
        
        <!-- Form to delete posts -->
        <form method="post">
            <?php wp_nonce_field( 'dmuk_bo_delete_posts_nonce' ); ?>
            <h2>Delete Test Posts</h2>
            <input type="submit" name="dmuk_bo_delete_posts" class="button button-secondary" value="Delete ALL Test Posts">
        </form>
    </div>
    <?php
}
?>
